# Generated by Django 5.2.17 on 2026-09-26 02:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/empleados/', verbose_name='Foto')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('fecha_contratacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Contratación')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='empleadosApp.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Detalle de Empleado',
                'verbose_name_plural': 'Detalles de Empleados',
                'db_table': 'detalle_empleados',
                'ordering': ['empleado__apellido', 'empleado__nombre'],
            },
        ),
    ]
