# Generated by Django 5.2.17 on 2026-09-23 15:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='vehiculos/')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculos',
                'ordering': ['marca', 'modelo', 'anio'],
            },
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('tipo_motor', models.CharField(max_length=50)),
                ('tipo_caja', models.CharField(max_length=50)),
                ('fecha_ultimo_servicio', models.DateField(default=django.utils.timezone.now)),
                ('kilometraje', models.IntegerField()),
                ('estado', models.CharField(choices=[('Bueno', 'En buen estado'), ('Intermedio', 'Condiciones intermedias'), ('Malas', 'En malas condiciónes')], max_length=50, verbose_name='Estado del vehículo')),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='vehiculosApp.vehiculo')),
            ],
            options={
                'verbose_name': 'Detalle del Vehículo',
                'verbose_name_plural': 'Detalles de Vehículos',
                'db_table': 'detalles_vehiculos',
                'ordering': ['vehiculo__marca', 'vehiculo__modelo', 'vehiculo__anio'],
            },
        ),
    ]
