# Generated by Django 5.2.17 on 2026-09-24 02:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='fecha_ultimo_servicio',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='vehiculosApp.vehiculo'),
        ),
    ]
