# Generated by Django 5.2.17 on 2026-09-23 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='fecha_ultimo_servicio',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.IntegerField(verbose_name='Año de fabricación'),
        ),
    ]
