# Generated by Django 5.2.17 on 2026-09-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculosApp', '0002_alter_detalle_fecha_ultimo_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/vehiculos/'),
        ),
    ]
