# Generated by Django 5.2.17 on 2026-09-24 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculosApp', '0003_alter_vehiculo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='creado',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='creado',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de creación'),
        ),
    ]
