# Generated by Django 5.2.17 on 2026-09-25 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculosApp', '0004_detalle_creado_vehiculo_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='vehiculo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='vehiculosApp.vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.IntegerField(verbose_name='Año de fabricación'),
        ),
    ]
