# Generated by Django 5.2.17 on 2026-09-24 02:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bujia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='codigo de la bujia')),
                ('nombre', models.CharField(max_length=100, verbose_name='bujia')),
                ('precio', models.PositiveIntegerField(verbose_name='precio de la bujia')),
                ('stock', models.IntegerField(default=0, verbose_name='stock de la bujia')),
                ('descripcion', models.CharField(max_length=200, verbose_name='descripcion de la bujia')),
                ('imagen', models.ImageField(upload_to='bujias/')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de creacion')),
            ],
            options={
                'verbose_name': 'bujia',
                'verbose_name_plural': 'bujias',
                'db_table': 'bujias',
                'ordering': ['nombre', 'precio'],
            },
        ),
        migrations.CreateModel(
            name='filtro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='codigo del filtro')),
                ('nombre', models.CharField(max_length=100, verbose_name='filtro')),
                ('precio', models.PositiveIntegerField(verbose_name='precio del filtro')),
                ('stock', models.IntegerField(default=0, verbose_name='stock del filtro')),
                ('descripcion', models.CharField(max_length=200, verbose_name='descripcion del filtro')),
                ('imagen', models.ImageField(upload_to='filtros/')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de creacion')),
            ],
            options={
                'verbose_name': 'filtro',
                'verbose_name_plural': 'filtros',
                'db_table': 'filtros',
                'ordering': ['nombre', 'precio'],
            },
        ),
        migrations.CreateModel(
            name='pastilla_freno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='codigo de la pastilla de freno')),
                ('nombre', models.CharField(max_length=100, verbose_name='pastilla de freno')),
                ('precio', models.PositiveIntegerField(verbose_name='precio de la pastilla de freno')),
                ('stock', models.IntegerField(default=0, verbose_name='stock de la pastilla de freno')),
                ('descripcion', models.CharField(max_length=200, verbose_name='descripcion de la pastilla de freno')),
                ('imagen', models.ImageField(upload_to='pastillas_freno/')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de creacion')),
            ],
            options={
                'verbose_name': 'pastilla de freno',
                'verbose_name_plural': 'pastillas de freno',
                'db_table': 'pastillas_freno',
                'ordering': ['nombre', 'precio'],
            },
        ),
    ]
