# Generated by Django 5.2.17 on 2026-09-24 11:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='descripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='descripcion del repuesto')),
            ],
            options={
                'verbose_name': 'descripcion',
                'verbose_name_plural': 'descripciones',
                'db_table': 'descripcion',
                'ordering': ['repuesto'],
            },
        ),
        migrations.CreateModel(
            name='repuestos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='codigo de los repuestos')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre de los repuestos')),
                ('precio', models.PositiveIntegerField(verbose_name='precio de los repuestos')),
                ('stock', models.IntegerField(default=0, verbose_name='stock de los repuestos')),
                ('detalle', models.CharField(max_length=200, verbose_name='detalle de los repuestos')),
                ('imagen', models.ImageField(upload_to='repuestos/')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de creacion')),
            ],
            options={
                'verbose_name': 'repuesto',
                'verbose_name_plural': 'repuestos',
                'db_table': 'repuestos',
                'ordering': ['nombre', 'precio'],
            },
        ),
        migrations.DeleteModel(
            name='bujia',
        ),
        migrations.DeleteModel(
            name='filtro',
        ),
        migrations.DeleteModel(
            name='pastilla_freno',
        ),
        migrations.AddField(
            model_name='descripcion',
            name='repuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repuestosApp.repuestos', verbose_name='repuesto'),
        ),
    ]
