# Generated by Django 5.2.17 on 2026-09-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestosApp', '0002_descripcion_repuestos_delete_bujia_delete_filtro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuestos',
            name='imagen',
            field=models.ImageField(upload_to='images/repuestos/'),
        ),
    ]
